Repository notobo15/online-train-ticket-reservations, pull requests merged in 2024-10, with the labels that each got.

#6 Feat/excel import
  pom.xml
  src/main/java/com/trainticketbooking/app/Entities/Booking.java
  src/main/java/com/trainticketbooking/app/Entities/CarriageSeatMapping.java
  src/main/java/com/trainticketbooking/app/Entities/PassengerType.java
  src/main/java/com/trainticketbooking/app/Entities/Price.java
  src/main/java/com/trainticketbooking/app/Entities/Province.java
  src/main/java/com/trainticketbooking/app/Entities/RailwayNetwork.java
  src/main/java/com/trainticketbooking/app/Entities/Route.java
  src/main/java/com/trainticketbooking/app/Entities/Seat.java
  src/main/java/com/trainticketbooking/app/Entities/SeatType.java
  src/main/java/com/trainticketbooking/app/Entities/Station.java
  src/main/java/com/trainticketbooking/app/Entities/Train.java
  src/main/java/com/trainticketbooking/app/Entities/TrainJourney.java
  src/main/java/com/trainticketbooking/app/Entities/TrainJourneyRouteMapping.java
  src/main/java/com/trainticketbooking/app/Entities/User.java
  src/main/java/com/trainticketbooking/app/Excels/ExcelReader.java
  src/main/java/com/trainticketbooking/app/Repos/CarriageSeatMappingRepository.java
  src/main/java/com/trainticketbooking/app/Repos/PassengerTypeRepository.java
  src/main/java/com/trainticketbooking/app/Repos/PriceRepository.java
  src/main/java/com/trainticketbooking/app/Repos/ProvinceRepository.java
  src/main/java/com/trainticketbooking/app/Repos/RouteRepository.java
  src/main/java/com/trainticketbooking/app/Repos/SeatTypeRepository.java
  src/main/java/com/trainticketbooking/app/Services/ICarriageSeatMappingService.java
  src/main/java/com/trainticketbooking/app/Services/IPassengerTypeService.java
  src/main/java/com/trainticketbooking/app/Services/IPriceService.java
  src/main/java/com/trainticketbooking/app/Services/IProvinceService.java
  src/main/java/com/trainticketbooking/app/Services/ISeatTypeService.java
  src/main/java/com/trainticketbooking/app/Services/impl/CarriageSeatMappingService.java
  src/main/java/com/trainticketbooking/app/Services/impl/PassengerTypeService.java
  src/main/java/com/trainticketbooking/app/Services/impl/PriceService.java
  src/main/java/com/trainticketbooking/app/Services/impl/ProvinceService.java
  src/main/java/com/trainticketbooking/app/Services/impl/RouteService.java
  src/main/java/com/trainticketbooking/app/Services/impl/SeatService.java
  src/main/java/com/trainticketbooking/app/Services/impl/SeatTypeService.java
  src/main/java/com/trainticketbooking/app/Services/impl/StationService.java
  src/main/java/com/trainticketbooking/app/Services/impl/TrainJourneyService.java
  src/main/resources/data/data.xlsx
Labels: bug, feat

#7 Feat/auth admin
  pom.xml
  src/main/java/com/trainticketbooking/app/Auths/CustomAccessDeniedHandler.java
  src/main/java/com/trainticketbooking/app/Auths/CustomAuthenticationFailureHandler.java
  src/main/java/com/trainticketbooking/app/Auths/CustomUserDetailsService.java
  src/main/java/com/trainticketbooking/app/Auths/SeedData.java
  src/main/java/com/trainticketbooking/app/Configs/SecurityConfig.java
  src/main/java/com/trainticketbooking/app/Controllers/AccessDeniedController.java
  src/main/java/com/trainticketbooking/app/Controllers/AuthController.java
  src/main/java/com/trainticketbooking/app/Entities/Role.java
  src/main/java/com/trainticketbooking/app/Entities/User.java
  src/main/java/com/trainticketbooking/app/Models/UserModel.java
  src/main/java/com/trainticketbooking/app/Repos/RoleRepository.java
  src/main/java/com/trainticketbooking/app/Services/IRoleService.java
  src/main/java/com/trainticketbooking/app/Services/IUserService.java
  src/main/java/com/trainticketbooking/app/Services/impl/RoleService.java
  src/main/java/com/trainticketbooking/app/Services/impl/UserService.java
  src/main/resources/templates/admin/auth/access-denied.html
  src/main/resources/templates/admin/auth/login.html
  src/main/resources/templates/admin/auth/register.html
Labels: feat

#10 added: integrate Swagger UI for client API
  pom.xml
  src/main/java/com/trainticketbooking/app/Configs/OpenAPIConfig.java
  src/main/resources/application.properties
Labels: feat

#12 Feat/admin routes
  src/main/java/com/trainticketbooking/app/Controllers/RoutesController.java
  src/main/java/com/trainticketbooking/app/Entities/Route.java
  src/main/java/com/trainticketbooking/app/Services/IRouteService.java
  src/main/java/com/trainticketbooking/app/Services/impl/RouteService.java
  src/main/resources/templates/admin/fragments/_sidebar.html
  src/main/resources/templates/admin/routes/create.html
  src/main/resources/templates/admin/routes/detail.html
  src/main/resources/templates/admin/routes/edit.html
  src/main/resources/templates/admin/routes/index.html
Labels: enhancement, feat

#13 added: complete admin roles
  src/main/java/com/trainticketbooking/app/Controllers/AdminRolesController.java
  src/main/java/com/trainticketbooking/app/Entities/Role.java
  src/main/java/com/trainticketbooking/app/Services/IRoleService.java
  src/main/java/com/trainticketbooking/app/Services/impl/RoleService.java
  src/main/resources/static/icons/role.svg
  src/main/resources/templates/admin/fragments/_sidebar.html
  src/main/resources/templates/admin/roles/create.html
  src/main/resources/templates/admin/roles/edit.html
  src/main/resources/templates/admin/roles/index.html
Labels: enhancement, feat
